---
- hosts: centos7
  become: True
  gather_facts: true
  name: Install prj2
  tasks:

    - name: Check prj2
      shell: cat /etc/profile.d/local_path_export.sh | grep prj2
      register: prj2_status 
      ignore_errors: True

    - name: Check OS version
      shell: cat /etc/centos-release
      register: os_status
    - debug:
        var: os_status

    - name: Install prj2 command
      shell: echo "alias prj2='. /.appl/.bin/prj2.bash'" >> /etc/profile.d/local_path_export.sh
      when: os_status.stdout == "CentOS Linux release 7.7.1908 (Core)" and  prj2_status.stdout == "" or os_status.stdout == "CentOS Linux release 7.9.2009 (Core)" and prj2_status.stdout == ""
    
    - name: Verify prj2
      shell: cat /etc/profile.d/local_path_export.sh | grep prj2
      register: prj2_outstatus
      ignore_errors: True
    - debug:
        var: prj2_outstatus
      