---
- hosts: centos7
  become: True
  gather_facts: true
  name: POST INSTALLATION STEPS
  tasks:

    - name: Check OS version
      shell: cat /etc/centos-release
      register: os_status
    - debug:
        var: os_status

    - name: Check resetGnome already installed
      shell: crontab -l | grep " /ASE/08_rnd/autodesk/resetGnome.sh"
      register: gnome_status
      ignore_errors: True
    - debug: 
        var: gnome_status

    - name: Check resetCore already installed
      shell: crontab -l | grep " /ASE/app/00_workStationSetup/core_clear.sh"
      register: core_status
      ignore_errors: True
    - debug: 
        var: core_status

    - name: Check NX already installed
      shell: crontab -l | grep "0 8 * * * /etc/NX/nxserver --restart"
      register: nx_status
      ignore_errors: True
    - debug: 
        var: nx_status

    - name: Check BAckup CRON
      shell: crontab -l | grep "/ASE/app/00_workStationSetup/./health_check.bin"
      register: backup_status
      ignore_errors: True
    - debug: 
        var: backup_status

    - name: SET CRON for GNOME RESET
      cron:
        name: "Setting Gnome Reset"
        minute: "*/10"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/ASE/08_rnd/autodesk/resetGnome.sh"
      when: os_status.stdout == "CentOS Linux release 7.7.1908 (Core)" and gnome_status.stdout == ""


    - name: SET CRON for CORE DELETION
      cron:
        name: "Deleting CORE FILES"
        minute: "*/30"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/ASE/app/00_workStationSetup/core_clear.sh"
      when: os_status.stdout == "CentOS Linux release 7.7.1908 (Core)" and core_status.stdout == ""
    
    
    - name: SET CRON for NX RESET
      cron:
        name: "Setting NX Reset"
        minute: "45"
        hour: "7"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/etc/NX/nxserver --restart"
      when: nx_status.stdout == ""

    - name: SET CRON for BACKUP
      cron:
        name: "Setting BACKUP CRON"
        minute: "30"
        hour: "23"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/ASE/app/00_workStationSetup/./health_check.bin"
      when: backup_status.stdout == ""

    - name: Check Installed Cron
      shell: crontab -l 
      register: nx_status
      ignore_errors: True
    - debug: 
        var: nx_status    